services:
  freepbx:
    image: tiredofit/freepbx:latest
    container_name: freepbx
    platform: linux/amd64
    restart: unless-stopped
    ports:
      - "8080:80"
      - "8443:443"
      - "8088:8088"
      - "5060:5060/udp"
      - "5060:5060/tcp"
      - "5160:5160/udp"
      - "18000-18100:18000-18100/udp"
    environment:
      - DB_EMBEDDED=TRUE
      - ADMIN_PASSWORD=admin
      - RTP_START=18000
      - RTP_FINISH=18100
      # Wait a bit before checking health/starting
    volumes:
      - freepbx_data:/data
      - freepbx_db:/var/lib/mysql
    networks:
      - default

networks:
  default:
    driver: bridge

volumes:
  freepbx_data:
  freepbx_db:
